- name: variables from inventory 
  hosts: web
  tasks:
  - name: print course information from inventory
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"