- name: Varibles preference 
  hosts: local
  connection: local
  vars:
    GREET: "PLAY"
  # vars_files:
  # - course.yaml
  vars_prompt:
  # - name: GREET
  #   prompt: Enter the value 
  #   private: false
  tasks:
  - name: print the variables
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"
  

# Preferences 
#1 Commands line args 
#2 Task Level
#3 files
#4 prompts
#5 