- name: Install nginx
  hosts: web
  become: yes
  tasks:
  - name: install ngix if RHEL
    ansible.builtin.dnf:
      name: nginx
      state: installed 
    when: ansible_os_family == "RedHat"
  - name: install nginx if Ubantu
    ansible.builtin.apt:
      name: nginx 
      state: installed
    when: ansible_os_family == "Debian"