- name: Installing all packages using loop
  hosts: web
  tasks:
  - name: Install Pacakages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - gcc
    - mysql
    - zip 
    - git
